name: 🧪 Test (PR) (Ubuntu)

# All PRs touching code will run tests on ubuntu/node/chromium

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "scripts/**"
      - "contributors.yml"
      - "**/*.md"

jobs:
  build:
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared/build.yml

  test-unit-ubuntu:
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared/test-unit.yml
    with:
      os: '["ubuntu-latest"]'
      node_version: '["latest"]'

  test-integration-ubuntu-chromium:
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared/test-integration.yml
    with:
      os: '["ubuntu-latest"]'
      node_version: '["latest"]'
      browser: '["chromium"]'
