name: PR (Full)

# PRs touching create-remix/remix-dev will also run on Windows and OSX

on:
  pull_request:
    paths:
      - "packages/create-remix/**"
      - "packages/remix-dev/**"
      - "!**/*.md"

jobs:
  unit-windows:
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-unit.yml
    with:
      os: "windows-latest"
      node_version: '["latest"]'

  integration-firefox:
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-integration.yml
    with:
      os: "ubuntu-latest"
      node_version: '["latest"]'
      browser: '["firefox"]'

  integration-edge:
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-integration.yml
    with:
      os: "windows-latest"
      node_version: '["latest"]'
      browser: '["edge"]'

  integration-webkit:
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-integration.yml
    with:
      os: "macos-latest"
      node_version: '["latest"]'
      browser: '["webkit"]'
